### ISSUE TITLE
3 comandos nao funciona

### ISSUE THREAD

**Issue by GabrielHTZTEST** [BotDesignerForDiscordBR/Bot-BDscript#12]
O de trabalhar o de sair e entrar nao funciona

**Comment by FlareVee** [comment]
Oi, o de entrar e sair funciona sim, apenas tente corrigí-lo de acordo com as novas normas do discord, espero ter ajudado :3

**Comment by moondarkcd** [comment]
> O de trabalhar o de sair e entrar nao funciona

Você tem que fazer uma variável com o nome da sua moeda, no valor de 0. Depois troque "trabalho" e "dinheiro" pelo nome da sua moeda
